#!/usr/bin/env bash
TOKEN="eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Ijg0OTY1ODExLWJlM2QtNGZiNi1hOWIxLWViNDgzMDhlZDhlMSIsInJvbGUiOiJzZWxsZXIiLCJpYXQiOjE3NzUzMDcxMTMsImV4cCI6MTc3Nzg5OTExM30.Z4n-MWB2nP_EDL5vIMxsd0KIl6dNktVEeVyPQK1hIOk"
API="https://wekasokobackend.up.railway.app"

post_req() {
  curl -s -X POST "$API/api/requests" \
    -H "Content-Type: application/json" \
    -H "Authorization: Bearer $TOKEN" \
    -d "$1" | python3 -c "import sys,json; d=json.load(sys.stdin); print(d.get('id','ERR: '+str(d)))" 2>/dev/null
}

echo "=== Creating 50 Buyer Requests ==="

post_req '{"title":"iPhone 13 or 14 in good condition","description":"Looking for iPhone 13 or 14, at least 128GB, Face ID working, no cracks on screen. Preferably with original charger and box. In Nairobi.","budget":75000,"county":"Nairobi","category":"Electronics","subcat":"Phones"}'
post_req '{"title":"Good secondhand laptop for university","description":"Need a laptop for software engineering coursework. At least i5, 8GB RAM, 256GB SSD. Dell, HP, Lenovo preferred. Budget is flexible for the right machine.","budget":45000,"county":"Nairobi","category":"Electronics","subcat":"Computers"}'
post_req '{"title":"Affordable 2-bedroom to rent Nairobi","description":"Looking for a 2-bedroom apartment or house in Nairobi, areas like South B, South C, Imara Daima, Donholm. Quiet, secure compound. Parking a bonus.","budget":25000,"county":"Nairobi","category":"Property","subcat":"Rentals"}'
post_req '{"title":"Toyota Premio or Allion 2012-2015","description":"Want a neat Premio or Allion in good condition, auto, petrol. Mileage under 100k. Must have logbook ready. Nairobi-registered preferred.","budget":1100000,"county":"Nairobi","category":"Vehicles","subcat":"Cars"}'
post_req '{"title":"Labrador Retriever puppy","description":"Looking for a healthy Labrador puppy, 6-10 weeks old. Yellow or black. Health checked and dewormed. Nairobi or Kiambu. Not from puppy mills.","budget":20000,"county":"Nairobi","category":"Pets","subcat":"Dogs"}'
post_req '{"title":"Second hand sofa set 5-7 seater","description":"Need a decent sofa set for a new apartment. 5 to 7 seater, any color that is not too worn. Free delivery to Embakasi would be ideal. Quick pickup.","budget":20000,"county":"Nairobi","category":"Furniture","subcat":"Sofas"}'
post_req '{"title":"Android phone good camera under 25k","description":"Looking for a phone with a great camera for content creation. Samsung, Xiaomi or Tecno preferred. At least 64GB storage. Must have all original accessories.","budget":25000,"county":"Mombasa","category":"Electronics","subcat":"Phones"}'
post_req '{"title":"Land for sale near Thika Road","description":"Looking to buy a plot near Thika Road, Ruiru or Juja area. Quarter or half acre. Needs to have title deed and accessible road. No brokers.","budget":800000,"county":"Kiambu","category":"Property","subcat":"Land"}'
post_req '{"title":"Used refrigerator single door","description":"Need a working single door fridge, any brand. At least 200L capacity. Moving to new place, unfurnished. Nairobi delivery preferred. Quick buy.","budget":15000,"county":"Nairobi","category":"Appliances","subcat":"Refrigerators"}'
post_req '{"title":"Honda or Yamaha motorcycle below 150cc","description":"Want a small motorcycle for town use. Good fuel economy. Clean papers. Not more than 2 years old. Any county, will travel to view.","budget":150000,"county":"Nairobi","category":"Vehicles","subcat":"Motorcycles"}'
post_req '{"title":"Office space for rent Westlands","description":"Startup looking for shared or small office space in Westlands or Upper Hill. High-speed internet, meeting room access. Open to serviced offices.","budget":20000,"county":"Nairobi","category":"Property","subcat":"Commercial"}'
post_req '{"title":"DSLR or mirrorless camera for events","description":"Starting events photography. Looking for a camera with at least one lens. Canon, Nikon or Sony. Budget includes body and lens combo.","budget":60000,"county":"Nairobi","category":"Electronics","subcat":"Cameras"}'
post_req '{"title":"Children school uniform sewing machine","description":"Small home sewing machine for making school uniforms. Straight stitch, lockstitch. Singer or Brother preferred. Must be in working condition.","budget":12000,"county":"Kisumu","category":"Business","subcat":"Machinery"}'
post_req '{"title":"4x4 pickup truck for farm use","description":"Looking for a pickup truck, Toyota Hilux, Ford Ranger or similar. 4WD, diesel preferred. Farm use in Nakuru. Mileage under 150k. Serious buyer.","budget":2000000,"county":"Nakuru","category":"Vehicles","subcat":"Cars"}'
post_req '{"title":"Stand fan or ceiling fan for office","description":"Need 2-3 stand fans or ceiling fans for a small office in Mombasa. Any good brand. Prefer energy efficient. New or slightly used.","budget":8000,"county":"Mombasa","category":"Appliances","subcat":"Cooling"}'
post_req '{"title":"Acoustic guitar for beginner","description":"My kid wants to learn guitar. Looking for a beginner acoustic guitar with good action. Full size or 3/4. Comes with picks and tuner if possible.","budget":8000,"county":"Nairobi","category":"Music","subcat":"Instruments"}'
post_req '{"title":"Graphic design laptop high RAM","description":"Need a laptop for Adobe Creative Suite. At least 16GB RAM, dedicated GPU, fast SSD. MacBook or Dell XPS or similar. Will trade my current laptop.","budget":120000,"county":"Nairobi","category":"Electronics","subcat":"Computers"}'
post_req '{"title":"Aquarium with fish setup complete","description":"Looking for a complete fish tank setup, at least 100 liters, with filter, heater, lights and fish. Freshwater preferred. For home decoration.","budget":15000,"county":"Nairobi","category":"Pets","subcat":"Fish"}'
post_req '{"title":"Restaurant equipment stainless steel tables","description":"Starting a small restaurant. Need stainless steel prep tables, commercial pots, gas burners, plates. Open to buying as a lot.","budget":80000,"county":"Nairobi","category":"Business","subcat":"Food & Beverage"}'
post_req '{"title":"Flat screen monitor 24-inch or bigger","description":"Need a monitor for home office, at least 24 inches, Full HD, HDMI. Dell, LG or Samsung preferred. New or less than 1 year old.","budget":18000,"county":"Nairobi","category":"Electronics","subcat":"Computers"}'
post_req '{"title":"Recliner chair for living room","description":"Looking for a recliner chair, single seat. Leather or fabric. Must recline fully. Any color that is neutral. Delivery to Lavington.","budget":18000,"county":"Nairobi","category":"Furniture","subcat":"Chairs"}'
post_req '{"title":"Toyota Noah or Voxy 2015 and above","description":"Family van in good condition. Auto, petrol or hybrid. Less than 80,000km. Good bodywork. Nairobi. Will finance part of it.","budget":1800000,"county":"Nairobi","category":"Vehicles","subcat":"Cars"}'
post_req '{"title":"Used gym treadmill for home","description":"Looking for a working treadmill for home use. Electric, speed up to 15 kmh. Foldable preferred for space. Nairobi, pickup possible.","budget":22000,"county":"Nairobi","category":"Sports","subcat":"Fitness"}'
post_req '{"title":"Cat for adoption Nairobi","description":"Looking to adopt a cat, any breed. Vaccinated and healthy. Indoor cat preferred as we live in an apartment. Happy to provide a loving home.","budget":5000,"county":"Nairobi","category":"Pets","subcat":"Cats"}'
post_req '{"title":"Inverter generator 2kva","description":"Need a quiet inverter generator for home backup. Honda or Yamaha brand preferred. At least 2kVA. Used is fine if working well.","budget":35000,"county":"Nairobi","category":"Electronics","subcat":"Power"}'
post_req '{"title":"Bed frame and mattress 5x6","description":"Need a 5x6 bed frame, wooden or wrought iron. Mattress too if possible. Moving to new house. Quick buy, easy collection from Nairobi.","budget":20000,"county":"Nairobi","category":"Furniture","subcat":"Beds"}'
post_req '{"title":"Video camera for YouTube content","description":"Starting a YouTube channel. Looking for a vlogging camera with flip screen. Sony ZV or Canon M50 type. Lens, mic, or accessories included a bonus.","budget":55000,"county":"Nairobi","category":"Electronics","subcat":"Cameras"}'
post_req '{"title":"Subaru Outback or Legacy 2010-2013","description":"Looking for a Subaru Outback or Legacy, auto, petrol. All-wheel drive. Clean interior. Not higher than 120,000km mileage. Nairobi or Kiambu.","budget":850000,"county":"Nairobi","category":"Vehicles","subcat":"Cars"}'
post_req '{"title":"Event tent 10x15 with tables and chairs","description":"Catering business needs a second event tent. 10x15 waterproof tent plus plastic tables and chairs. Good condition. Eldoret area delivery possible.","budget":60000,"county":"Eldoret","category":"Business","subcat":"Events"}'
post_req '{"title":"Plot to buy in Rongai or Kiserian","description":"Looking for half acre plot in Rongai, Kiserian or Ngong. Road accessible. Title deed or allotment letter. Serious purchase, funds ready.","budget":700000,"county":"Kajiado","category":"Property","subcat":"Land"}'
post_req '{"title":"Smart TV 43-inch any brand","description":"Looking for a 43-inch smart TV, any good brand. Android TV preferred. HDMI ports. For bedroom use. New or barely used. Nairobi delivery.","budget":25000,"county":"Nairobi","category":"Electronics","subcat":"TVs"}'
post_req '{"title":"Rowing machine for home gym","description":"Looking for a rowing machine in good condition. Any brand. Air or water resistance preferred. Will self-collect in Nairobi.","budget":30000,"county":"Nairobi","category":"Sports","subcat":"Fitness"}'
post_req '{"title":"Secondhand school desk and chair sets","description":"Starting a tuition center. Need 20 sets of pupil desks and chairs. Metal frame, good condition. Bulk purchase. Nairobi area.","budget":40000,"county":"Nairobi","category":"Furniture","subcat":"Office"}'
post_req '{"title":"Kitten or small dog for apartment","description":"Looking for a small dog or kitten that can live in an apartment. Trained or easy to train. Vaccinated. Small breeds preferred, budget is flexible.","budget":12000,"county":"Nairobi","category":"Pets","subcat":"Dogs"}'
post_req '{"title":"Secondhand solar panel system 200W","description":"Looking for solar panels and controller for rural home. At least 200W. Includes battery and inverter if possible. Eldoret or Nakuru pickup.","budget":30000,"county":"Nakuru","category":"Electronics","subcat":"Power"}'
post_req '{"title":"Catering pots and sufurias large","description":"Starting a catering service. Need large cooking pots, sufurias 20L and above, aluminum or steel. Good working condition. Kisumu or Nairobi.","budget":15000,"county":"Kisumu","category":"Business","subcat":"Food & Beverage"}'
post_req '{"title":"3-bedroom house to rent Nakuru","description":"Looking for a 3-bedroom house in Nakuru, near town or Pipeline. Clean, secure. Parking and water must be available. Ready to move in soon.","budget":20000,"county":"Nakuru","category":"Property","subcat":"Rentals"}'
post_req '{"title":"Husqvarna or Stihl chainsaw","description":"Need a chainsaw for timber work on my farm. Husqvarna or Stihl, bar length at least 18 inches. Used is okay if well maintained.","budget":35000,"county":"Eldoret","category":"Garden","subcat":"Tools"}'
post_req '{"title":"Secondhand sewing machine home use","description":"Need a home use sewing machine. Singer or Brother preferred. Must be electric and able to do zigzag stitch. Under 10,000. Nairobi.","budget":9000,"county":"Nairobi","category":"Business","subcat":"Machinery"}'
post_req '{"title":"Mountain bike for adult commuting","description":"Looking for a mountain or hybrid bike for daily commuting. 26 or 27.5-inch wheels. Gears, good brakes. Not too heavy. Nairobi.","budget":18000,"county":"Nairobi","category":"Sports","subcat":"Cycling"}'
post_req '{"title":"Gas cooker 4-burner with oven","description":"Need a 4-burner gas cooker with oven for a restaurant. Any brand. Good working condition. Mombasa. Urgent need, ready to buy immediately.","budget":18000,"county":"Mombasa","category":"Appliances","subcat":"Kitchen"}'
post_req '{"title":"PlayStation 5 or Xbox Series X","description":"Looking for a gaming console for my son. PS5 or Xbox Series X. Original, no modded. With at least one controller. Nairobi delivery.","budget":60000,"county":"Nairobi","category":"Electronics","subcat":"Gaming"}'
post_req '{"title":"Stationery business supplies wholesale","description":"Buying stationery in bulk for school supply business. Notebooks, pens, rulers, geometry sets. Looking for supplier or someone with stock.","budget":50000,"county":"Nairobi","category":"Business","subcat":"Stationery"}'
post_req '{"title":"Diesel generator 5kva for business","description":"Need a diesel generator for a shop that experiences frequent outages. 5kVA minimum. Quiet preferred. Any condition if working. Mombasa.","budget":80000,"county":"Mombasa","category":"Electronics","subcat":"Power"}'
post_req '{"title":"Secondhand car Vitz or Demio 2012+","description":"First car buyer. Looking for Vitz or Demio from 2012. Low mileage, auto, no major accidents. Full logbook. Nairobi. Budget is firm.","budget":600000,"county":"Nairobi","category":"Vehicles","subcat":"Cars"}'
post_req '{"title":"Baby stroller and car seat combo","description":"Expecting a baby soon. Looking for a good quality stroller and car seat. Preferably a combo set. Graco or Chicco brand. Good condition.","budget":15000,"county":"Nairobi","category":"Baby","subcat":"Travel"}'
post_req '{"title":"Commercial freezer chest 200L+","description":"Need a chest freezer for a butchery. At least 200L. Any brand. Working perfectly. Nakuru or Nairobi area. Urgent, ready to buy today.","budget":35000,"county":"Nakuru","category":"Appliances","subcat":"Refrigerators"}'
post_req '{"title":"DJ equipment mixer and speakers","description":"Starting a DJ business. Looking for a mixer, 2 powered speakers and a controller. Any good brand. Used is fine if in working condition.","budget":80000,"county":"Nairobi","category":"Music","subcat":"DJ Equipment"}'
post_req '{"title":"Secondhand piano or keyboard 61 keys+","description":"My daughter is learning piano. Looking for an upright piano or 61-key keyboard with weighted keys and sustain pedal. Nairobi or Kiambu.","budget":25000,"county":"Nairobi","category":"Music","subcat":"Instruments"}'
post_req '{"title":"Office chairs good quality 10 pieces","description":"Buying 10 office chairs for a new office setup. Wheeled, adjustable height, armrests. Medium quality okay. Nairobi CBD or Westlands. Quick deal.","budget":50000,"county":"Nairobi","category":"Furniture","subcat":"Office"}'

echo ""
echo "=== Done creating buyer requests ==="
